algoritmo "salario-hora"

var dias: real
   horas: real
   dias_trabalhados: real
   salario: real
   salario_dia: real
   salario_hora:real



inicio
   escreva ("Digite os dias trabalhados:")
   leia (dias)

   salario_hora<- 25
   horas <- 8
   
   salario_dia <- salario_hora*horas
   
   salario <- salario_dia* dias
   
   escreval ("Seu salário será de:", salario, "R$")







fimalgoritmo